name: Build Component in Native Environment

on:
  push:
    branches: [ main, 'sprint/**', 'release/**', develop ]
  pull_request:
    branches: [ main, 'sprint/**', 'release/**', topic/RDK*, develop ]

jobs:
  build-entservices-on-pr:
    name: Build entservices-appmanagers component in github rdkcentral
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        compiler: [ gcc, clang ]
        coverage: [ with-coverage, without-coverage ]
        exclude:
          - compiler: clang
            coverage: with-coverage
          - compiler: clang
            coverage: without-coverage
          - compiler: gcc
            coverage: without-coverage
    container:
      image: ghcr.io/rdkcentral/docker-rdk-ci:latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: native build
        run: |
          sh -x build_dependencies.sh
          sh -x cov_build.sh
        env:
          GITHUB_TOKEN: ${{ secrets.RDKCM_RDKE }}