name: Build Component in Native Environment

on:
  push:
    branches: [ main, 'sprint/**', 'release/**', develop ]
  pull_request:
    branches: [ main, 'sprint/**', 'release/**', topic/RDK*, develop ]

jobs:
  build-entservices-on-pr:
    name: Build entservices-appmanagers component in github rdkcentral
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        compiler: [ gcc, clang ]
        coverage: [ with-coverage, without-coverage ]
        exclude:
          - compiler: clang
            coverage: with-coverage
          - compiler: clang
            coverage: without-coverage
          - compiler: gcc
            coverage: without-coverage
    container:
      image: ghcr.io/rdkcentral/docker-rdk-ci:latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install packages
        run: |
          apt update
          apt install -y libsqlite3-dev libcurl4-openssl-dev valgrind lcov clang libsystemd-dev libboost-all-dev libwebsocketpp-dev meson libcunit1 libcunit1-dev curl protobuf-compiler-grpc libgrpc-dev libgrpc++-dev libjsoncpp-dev

      - name: Build mocks
        run: >
          cmake
          -S "$GITHUB_WORKSPACE/entservices-testframework/Tests/mocks"
          -B build/mocks
          -DBUILD_SHARED_LIBS=ON
          -DRDK_SERVICES_L1_TEST=ON
          -DUSE_THUNDER_R4=ON
          -DCMAKE_TOOLCHAIN_FILE="${{ env.TOOLCHAIN_FILE }}"
          -DCMAKE_INSTALL_PREFIX="$GITHUB_WORKSPACE/install/usr"
          -DCMAKE_MODULE_PATH="$GITHUB_WORKSPACE/install/tools/cmake"
          -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}
          -DCMAKE_CXX_FLAGS="
          -DEXCEPTIONS_ENABLE=ON
          -DUSE_THUNDER_R4=ON
          -DTHUNDER_VERSION=4
          -DTHUNDER_VERSION_MAJOR=4
          -DTHUNDER_VERSION_MINOR=4
          -DRDK_SERVICES_L1_TEST
          -I $GITHUB_WORKSPACE/entservices-testframework/Tests/headers
          -I $GITHUB_WORKSPACE/entservices-testframework/Tests/headers/audiocapturemgr
          -I $GITHUB_WORKSPACE/entservices-testframework/Tests/headers/rdk/ds
          -I $GITHUB_WORKSPACE/entservices-testframework/Tests/headers/rdk/iarmbus
          -I $GITHUB_WORKSPACE/entservices-testframework/Tests/headers/rdk/iarmmgrs-hal
          -I $GITHUB_WORKSPACE/entservices-testframework/Tests/headers/ccec/drivers
          -I $GITHUB_WORKSPACE/entservices-testframework/Tests/headers/network
          -I $GITHUB_WORKSPACE/entservices-testframework/Tests
          -I $GITHUB_WORKSPACE/entservices-infra/helpers
          -I $GITHUB_WORKSPACE/Thunder/Source
          -I $GITHUB_WORKSPACE/Thunder/Source/core
          -I $GITHUB_WORKSPACE/install/usr/include
          -I ./usr/include/libdrm
          -include $GITHUB_WORKSPACE/entservices-testframework/Tests/mocks/devicesettings.h
          -include $GITHUB_WORKSPACE/entservices-testframework/Tests/mocks/Iarm.h
          -include $GITHUB_WORKSPACE/entservices-testframework/Tests/mocks/Rfc.h
          -include $GITHUB_WORKSPACE/entservices-testframework/Tests/mocks/RBus.h
          -include $GITHUB_WORKSPACE/entservices-testframework/Tests/mocks/Telemetry.h
          -include $GITHUB_WORKSPACE/entservices-testframework/Tests/mocks/Udev.h
          -include $GITHUB_WORKSPACE/entservices-testframework/Tests/mocks/maintenanceMGR.h
          -include $GITHUB_WORKSPACE/entservices-testframework/Tests/mocks/pkg.h
          -include $GITHUB_WORKSPACE/entservices-testframework/Tests/mocks/secure_wrappermock.h
          -include $GITHUB_WORKSPACE/entservices-testframework/Tests/mocks/wpa_ctrl_mock.h
          -include $GITHUB_WORKSPACE/entservices-testframework/Tests/mocks/readprocMockInterface.h
          -include $GITHUB_WORKSPACE/entservices-testframework/Tests/mocks/gdialservice.h
          --coverage
          -Wall -Wno-unused-result -Wno-deprecated-declarations -Wno-error=format=
          -Wl,-wrap,system -Wl,-wrap,popen -Wl,-wrap,syslog -Wl,-wrap,v_secure_system -Wl,-wrap,v_secure_popen -Wl,-wrap,v_secure_pclose -Wl,-wrap,unlink -Wl,-wrap,v_secure_system -Wl,-wrap,pclose -Wl,-wrap,setmntent -Wl,-wrap,getmntent
          -DENABLE_TELEMETRY_LOGGING
          -DUSE_IARMBUS
          -DENABLE_SYSTEM_GET_STORE_DEMO_LINK
          -DENABLE_DEEP_SLEEP
          -DENABLE_SET_WAKEUP_SRC_CONFIG
          -DENABLE_THERMAL_PROTECTION
          -DUSE_DRM_SCREENCAPTURE
          -DHAS_API_SYSTEM
          -DHAS_API_POWERSTATE
          -DHAS_RBUS
          -DENABLE_DEVICE_MANUFACTURER_INFO"
          &&
          cmake --build build/mocks -j8
          &&
          cmake --install build/mocks
          
      - name: native build
        run: |
          sh -x build_dependencies.sh
          sh -x cov_build.sh
        env:
          GITHUB_TOKEN: ${{ secrets.RDKCM_RDKE }}