name: Build Component in Native Environment

on:
  push:
    branches: [ main, 'sprint/**', 'release/**', develop ]
  pull_request:
    branches: [ main, 'sprint/**', 'release/**', topic/RDK*, develop ]

jobs:
  build-entservices-on-pr:
    name: Build entservices-appmanagers component in github rdkcentral
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/rdkcentral/docker-rdk-ci:latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Checkout entservices-testframework
        uses: actions/checkout@v3
        with:
          repository: rdkcentral/entservices-testframework
          path: entservices-testframework
          ref: develop
          token: ${{ secrets.RDKCM_RDKE }}

      - name: Install packages
        run: |
          apt update
          apt install -y libsqlite3-dev libcurl4-openssl-dev valgrind lcov clang libsystemd-dev libboost-all-dev libwebsocketpp-dev meson libcunit1 libcunit1-dev curl protobuf-compiler-grpc libgrpc-dev libgrpc++-dev libjsoncpp-dev

      - name: native build
        run: |
          sh -x build_dependencies.sh
          sh -x cov_build.sh
        env:
          GITHUB_TOKEN: ${{ secrets.RDKCM_RDKE }}